name: Daily Crypto Prediction Update

on:
  schedule:
    - cron: '0 0 * * *'  # Menjalankan setiap hari pukul 02:00 UTC (09:00 WIB)
  workflow_dispatch:      # Bisa dijalankan manual juga

jobs:
  run-daily-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily prediction script
        run: python run_daily_prediction.py

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git pull --rebase origin main
          git add .
          git commit -m "🗓️ Update prediksi harian [CI]" || echo "No changes to commit"
          git push https://sintanastalia:${{ secrets.HF_TOKEN }}@huggingface.co/spaces/sintanastalia/crypto-prediction HEAD:main
