name: Daily Prediction

on:
  schedule:
    - cron: '0 0 * * *'  # Setiap hari pukul 00:00 UTC
  workflow_dispatch:     # Bisa dijalankan manual dari GitHub juga

jobs:
  run-daily-prediction:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily prediction script
        run: python run_daily_prediction.py

      - name: Commit prediction results
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add 1_data_realtime/prediction/
          git commit -m "Update daily predictions" || echo "No changes to commit"
          git push
